on:
  schedule:
#    - cron: '* * * * *'

name: update-data

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Install cURL Headers
        run: sudo apt-get install libcurl4-openssl-dev
    
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
      
      - uses: r-lib/actions/setup-renv@v2
      
      - name: Update data
        run: Rscript -e 'source("R/functions.R")'
      
      - name: Commit Results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit data/wikipedia_pageviews.csv -m 'Update data' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
